### ISSUE TITLE
How to access services of Symfony in ExtDirect bundle?

### ISSUE THREAD

**Issue by cipherchien** [teqneers/ext-direct-bundle#1]
Hi,

The bundle is elegant, but I have one question. 
How to access services of Symfony in ExtDirect Service?

Thank you.

**Comment by sgehrig** [comment]
There are three options actually:
- you make your service **ContainerAware** by implementing the Symfony DI `ContainerAwareInterface` and your service will have the DI container automatically injected (**not recommended** but doable)
- you add the service id to the `TQ\ExtDirect\Annotation\Action` annotation like this: `@Direct\Action("my.service")`
- you add the `tq_extdirect.service` tag to your service definition (this is the same as the second option but just the other way round) - this is not documented at the moment however.
