### ISSUE TITLE
composer require teqneers/ext-direct-bundle problem

### ISSUE THREAD

**Issue by middlebrain** [teqneers/ext-direct-bundle#3]
The installation of this package with

```composer require teqneers/ext-direct-bundle```

results in the following problem:
```Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for teqneers/ext-direct-bundle ^3.1 -> satisfiable by teqneers/ext-direct-bundle[3.1.0].
    - teqneers/ext-direct-bundle 3.1.0 requires teqneers/ext-direct 3.1.x-dev -> satisfiable by teqneers/ext-direct[3.1.x-dev] but these conflict with your requirements or minimum-stability.

Installation failed, deleting ./composer.json.
```

Reason for this is the following version constraint in your ```composer.json```:
```
...
"teqneers/ext-direct": "3.1.x-dev",
...
```
This forces a ```"minimum-stability": "dev"``` in the users global ```config.json``` or local ```composer.json```. If you don't have a special reason for this: Can you relax the version constraint to something like
```
...
"teqneers/ext-direct": "^3.1",
...
```
?

Thanks.

**Comment by sgehrig** [comment]
@middlebrain Sorry! Yes, that was a mistake. Should be fixed now.
